/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as appImport } from './routes/__app'
import { Route as IndexImport } from './routes/index'
import { Route as ShareReportIdImport } from './routes/share/$reportId'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as appResearchIndexImport } from './routes/__app/research/index'
import { Route as appResearchIdIndexImport } from './routes/__app/research/$id/index'

// Create/Update Routes

const appRoute = appImport.update({
  id: '/__app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ShareReportIdRoute = ShareReportIdImport.update({
  id: '/share/$reportId',
  path: '/share/$reportId',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const appResearchIndexRoute = appResearchIndexImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => appRoute,
} as any)

const appResearchIdIndexRoute = appResearchIdIndexImport.update({
  id: '/research/$id/',
  path: '/research/$id/',
  getParentRoute: () => appRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__app': {
      id: '/__app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/share/$reportId': {
      id: '/share/$reportId'
      path: '/share/$reportId'
      fullPath: '/share/$reportId'
      preLoaderRoute: typeof ShareReportIdImport
      parentRoute: typeof rootRoute
    }
    '/__app/research/': {
      id: '/__app/research/'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof appResearchIndexImport
      parentRoute: typeof appImport
    }
    '/__app/research/$id/': {
      id: '/__app/research/$id/'
      path: '/research/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof appResearchIdIndexImport
      parentRoute: typeof appImport
    }
  }
}

// Create and export the route tree

interface appRouteChildren {
  appResearchIndexRoute: typeof appResearchIndexRoute
  appResearchIdIndexRoute: typeof appResearchIdIndexRoute
}

const appRouteChildren: appRouteChildren = {
  appResearchIndexRoute: appResearchIndexRoute,
  appResearchIdIndexRoute: appResearchIdIndexRoute,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof appRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/share/$reportId': typeof ShareReportIdRoute
  '/research': typeof appResearchIndexRoute
  '/research/$id': typeof appResearchIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof appRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/share/$reportId': typeof ShareReportIdRoute
  '/research': typeof appResearchIndexRoute
  '/research/$id': typeof appResearchIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__app': typeof appRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/share/$reportId': typeof ShareReportIdRoute
  '/__app/research/': typeof appResearchIndexRoute
  '/__app/research/$id/': typeof appResearchIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/share/$reportId'
    | '/research'
    | '/research/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/share/$reportId'
    | '/research'
    | '/research/$id'
  id:
    | '__root__'
    | '/'
    | '/__app'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/share/$reportId'
    | '/__app/research/'
    | '/__app/research/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRoute: typeof appRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ShareReportIdRoute: typeof ShareReportIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRoute: appRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ShareReportIdRoute: ShareReportIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__app",
        "/auth/sign-in",
        "/auth/sign-up",
        "/share/$reportId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__app": {
      "filePath": "__app.tsx",
      "children": [
        "/__app/research/",
        "/__app/research/$id/"
      ]
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/share/$reportId": {
      "filePath": "share/$reportId.tsx"
    },
    "/__app/research/": {
      "filePath": "__app/research/index.tsx",
      "parent": "/__app"
    },
    "/__app/research/$id/": {
      "filePath": "__app/research/$id/index.tsx",
      "parent": "/__app"
    }
  }
}
ROUTE_MANIFEST_END */
