/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as appImport } from './routes/__app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as appResearchIndexImport } from './routes/__app/research/index'
import { Route as appLibraryIndexImport } from './routes/__app/library/index'
import { Route as appResearchChatIdIndexImport } from './routes/__app/research/chat/$id/index'

// Create/Update Routes

const appRoute = appImport.update({
  id: '/__app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const appResearchIndexRoute = appResearchIndexImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => appRoute,
} as any)

const appLibraryIndexRoute = appLibraryIndexImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => appRoute,
} as any)

const appResearchChatIdIndexRoute = appResearchChatIdIndexImport.update({
  id: '/research/chat/$id/',
  path: '/research/chat/$id/',
  getParentRoute: () => appRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__app': {
      id: '/__app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/__app/library/': {
      id: '/__app/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof appLibraryIndexImport
      parentRoute: typeof appImport
    }
    '/__app/research/': {
      id: '/__app/research/'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof appResearchIndexImport
      parentRoute: typeof appImport
    }
    '/__app/research/chat/$id/': {
      id: '/__app/research/chat/$id/'
      path: '/research/chat/$id'
      fullPath: '/research/chat/$id'
      preLoaderRoute: typeof appResearchChatIdIndexImport
      parentRoute: typeof appImport
    }
  }
}

// Create and export the route tree

interface appRouteChildren {
  appLibraryIndexRoute: typeof appLibraryIndexRoute
  appResearchIndexRoute: typeof appResearchIndexRoute
  appResearchChatIdIndexRoute: typeof appResearchChatIdIndexRoute
}

const appRouteChildren: appRouteChildren = {
  appLibraryIndexRoute: appLibraryIndexRoute,
  appResearchIndexRoute: appResearchIndexRoute,
  appResearchChatIdIndexRoute: appResearchChatIdIndexRoute,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof appRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/library': typeof appLibraryIndexRoute
  '/research': typeof appResearchIndexRoute
  '/research/chat/$id': typeof appResearchChatIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof appRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/library': typeof appLibraryIndexRoute
  '/research': typeof appResearchIndexRoute
  '/research/chat/$id': typeof appResearchChatIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__app': typeof appRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/__app/library/': typeof appLibraryIndexRoute
  '/__app/research/': typeof appResearchIndexRoute
  '/__app/research/chat/$id/': typeof appResearchChatIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/library'
    | '/research'
    | '/research/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/library'
    | '/research'
    | '/research/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/__app'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/__app/library/'
    | '/__app/research/'
    | '/__app/research/chat/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRoute: typeof appRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRoute: appRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__app",
        "/auth/sign-in",
        "/auth/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__app": {
      "filePath": "__app.tsx",
      "children": [
        "/__app/library/",
        "/__app/research/",
        "/__app/research/chat/$id/"
      ]
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/__app/library/": {
      "filePath": "__app/library/index.tsx",
      "parent": "/__app"
    },
    "/__app/research/": {
      "filePath": "__app/research/index.tsx",
      "parent": "/__app"
    },
    "/__app/research/chat/$id/": {
      "filePath": "__app/research/chat/$id/index.tsx",
      "parent": "/__app"
    }
  }
}
ROUTE_MANIFEST_END */
